name: CI/CD Pipeline with Environments

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t tbd-todo-app:latest .

      - name: Save Docker Image for Deployment
        run: docker save tbd-todo-app:latest | gzip > tbd-todo-app.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: tbd-todo-app.tar.gz

  deploy-dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Deploy to Dev
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp tbd-todo-app.tar.gz user@your-test-server:/home/user/
          ssh user@your-test-server "
            cd /home/user &&
            docker load < tbd-todo-app.tar.gz &&
            export $(cat /home/user/tbd-todo-app/.env.dev | xargs) &&
            docker-compose --env-file /home/user/tbd-todo-app/.env.dev up -d --build
          "

  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Deploy to Staging
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp tbd-todo-app.tar.gz user@your-test-server:/home/user/
          ssh user@your-test-server "
            cd /home/user &&
            docker load < tbd-todo-app.tar.gz &&
            export $(cat /home/user/tbd-todo-app/.env.staging | xargs) &&
            docker-compose --env-file /home/user/tbd-todo-app/.env.staging up -d --build
          "

  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp tbd-todo-app.tar.gz user@your-test-server:/home/user/
          ssh user@your-test-server "
            cd /home/user &&
            docker load < tbd-todo-app.tar.gz &&
            export $(cat /home/user/tbd-todo-app/.env.prod | xargs) &&
            docker-compose --env-file /home/user/tbd-todo-app/.env.prod up -d --build
          "
