name: CI/CD Pipeline with Environments

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t tbd-todo-app:latest .

      - name: Save Docker Image for Deployment
        run: docker save tbd-todo-app:latest | gzip > tbd-todo-app.tar.gz

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: tbd-todo-app.tar.gz

  deploy-dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Install sshpass
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass


      - name: Deploy to Dev
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp tbd-todo-app.tar.gz davina@159.65.211.46:/home/davina/
        sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "
          cd /home/davina &&
          docker load < tbd-todo-app.tar.gz &&
          export \$(cat /home/davina/tbd-todo-app/.env.dev | xargs) &&
          docker-compose --env-file /home/davina/tbd-todo-app/.env.dev up -d --build
        "

  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Install sshpass
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Staging
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp tbd-todo-app.tar.gz davina@159.65.211.46:/home/davina/
        sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "
          cd /home/davina &&
          docker load < tbd-todo-app.tar.gz &&
          export \$(cat /home/davina/tbd-todo-app/.env.staging | xargs) &&
          docker-compose --env-file /home/davina/tbd-todo-app/.env.staging up -d --build
        "

  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Install sshpass
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass


      - name: Deploy to Production
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp tbd-todo-app.tar.gz davina@159.65.211.46:/home/davina/
        sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "
          cd /home/davina &&
          docker load < tbd-todo-app.tar.gz &&
          export \$(cat /home/davina/tbd-todo-app/.env.prod | xargs) &&
          docker-compose --env-file /home/davina/tbd-todo-app/.env.prod up -d --build
        "
