name: CI/CD Pipeline with Environments

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t tbd-todo-app:latest .

      - name: Save Docker Image for Deployment
        run: docker save tbd-todo-app:latest | gzip > tbd-todo-app.tar.gz

      - name: Create Deployment Package
        run: |
          tar -czf deploy.tar.gz * .env* tbd-todo-app.tar.gz

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deploy-package
          path: deploy.tar.gz

  deploy-dev:
    name: Deploy to Dev Environment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: deploy-package

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Dev
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "mkdir -p /home/davina/tbd-todo-app"
          sshpass -p "$SSH_PASSWORD" scp deploy.tar.gz davina@159.65.211.46:/home/davina/tbd-todo-app/
          
          sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "
            cd /home/davina/tbd-todo-app &&
            tar -xzf deploy.tar.gz &&
            sudo docker load < tbd-todo-app.tar.gz &&
            sudo docker-compose --env-file .env.dev up -d --build
          "

  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: deploy-package

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Staging
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "mkdir -p /home/davina/tbd-todo-app"
          sshpass -p "$SSH_PASSWORD" scp deploy.tar.gz davina@159.65.211.46:/home/davina/tbd-todo-app/
          
          sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "
            cd /home/davina/tbd-todo-app &&
            tar -xzf deploy.tar.gz &&
            sudo docker load < tbd-todo-app.tar.gz &&
            sudo docker-compose --env-file .env.staging up -d --build
          "

  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: deploy-package

      - name: Install sshpass
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Production
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "mkdir -p /home/davina/tbd-todo-app"
          sshpass -p "$SSH_PASSWORD" scp deploy.tar.gz davina@159.65.211.46:/home/davina/tbd-todo-app/
          
          sshpass -p "$SSH_PASSWORD" ssh davina@159.65.211.46 "
            cd /home/davina/tbd-todo-app &&
            tar -xzf deploy.tar.gz &&
            sudo docker load < tbd-todo-app.tar.gz &&
            sudo docker-compose --env-file .env.prod up -d --build
          "